- README.md
- core/src/main/scala/com/karumi/shot/domain/model.scala
- core/src/test/scala/com/karumi/shot/domain/ConfigSpec.scala
- shot/src/main/scala/com/karumi/shot/ShotPlugin.scala
* **Issue:** https://github.com/Karumi/Shot/issues/18
The objective for this PR is to fix two problems:
1) Adjust gradle compile mode to the new gradle compile mode required by new gradle versions and giving support for the old one. To do this we will detect the gradle version and modify compile for implementation.
2) Fix a problem with an exception in the dex when including a library that contains a reference to dexmaker.
I added a new method that detects the gradle versión and provides implementationAndroidTest or compileAndroidTest depends on the version.
I change the way that adds the facebook library moving the include of the library when the dependencies tree is going to be processed, search if the Facebook dependency exists in the project and include it if this is missing.
1) …
> 18 bug gradle 34

- core/src/main/scala/com/karumi/shot/domain/model.scala
- core/src/test/scala/com/karumi/shot/domain/ConfigSpec.scala
- shot-consumer/app/build.gradle
- shot-consumer/app/src/androidTest/java/com/karumi/screenshot/ScreenshotTest.java
- shot-consumer/build.gradle
- shot-consumer/gradle/wrapper/gradle-wrapper.properties
* **Issue:** #42 
* To increment facebook screenshot testing library to 0.8.0
* To upgrade android support library to 28
* Increase facebook library version to 0.8.0
* Increase android support library to 28
* Start a new emulator
* Run './gradlew executeScreenshotTests -Precord'
* Run './gradlew executeScreenshotTests' 
And check if everything works properly
> Update facebook dependency to 0.8.0

- core/src/main/scala/com/karumi/shot/domain/model.scala
- core/src/test/scala/com/karumi/shot/domain/ConfigSpec.scala
- shot/src/main/scala/com/karumi/shot/ShotPlugin.scala
Fixes #48 . Use only ``androidTestImplementation`` instead of ``testImplementation`` because we've noticed this is not working properly on the latest project we've been working on.
We've removed the old code and the coverage associated.
🤖
> Use only androidTestImplementation

- README.md
After the update in https://github.com/Karumi/Shot/releases/tag/2.1.0 the readme wasn't updated to reflect the lib bump.
> Add newest facebook lib version to README.md

- shot/src/main/scala/com/karumi/shot/ShotExtension.scala
- shot/src/main/scala/com/karumi/shot/ShotPlugin.scala
* **Issue:** https://github.com/Karumi/Shot/issues/49
This allows you to integrate remote service such as Firebase Test Lab with screenshot reporting.
We provide a flag to disable instrumentation tests that run as part of screenshot task suite. 
```
shot {
runInstrumentationTests = false
}
```
User can now instead provide screenshot data in **screenshots/screenshots-default** folder and just call **executeScreenshotTests**.
- Add fake screenshot data to **shots-consumer/app/screenshots/screenshots-default** 
- Disable the `runInstrumentationTests` flag
- Run `executeScreenshotTests`
> Enable executing screenshot task without running instrumentation

- README.md
Update `README` file to reference the expected configuration name that is `runInstrumentation` not `runInstrumentationTests`
> Fix configuration name to not run instrumentation tests

- shot-consumer/build.gradle
- shot/src/main/scala/com/karumi/shot/ShotPlugin.scala
* **Issue:** Fixes #63 
Provide support for the Android Gradle Plugin 3.5.X
We've noticed the part of the gradle plugin asking for the adb path was initialized before the Android Gradle Plugin is un and running and this was breaking the build. We've moved the adb path configuration to a different plugin setup stage so we get this value once it's ready.
Additionally, we've updated the example project provided in this repository named ``shot-consumer`` to use the Android Gradle Plugin version 3.5.0 so we ensure this issue will never happen again.
🤖
> Add support for android gradle pluggin 3.5.0

- core/src/main/scala/com/karumi/shot/reports/ExecutionReporter.scala
* **Issue:** Hard to find failed tests when you have a large tests suite (200 tests) Closes #24 
Show failed tests first. Failed tests are of much higher interest.
Group screenshots by test result - failed come first, passed come afterwards.
Didn't find any tests on HTML report markup. Not sure if this PR should introduce such tests. LMKWYT.
> Show failed tests first - they are of much higher interest.

- README.md
- core/build.gradle
- core/src/main/scala/com/karumi/shot/Shot.scala
- core/src/main/scala/com/karumi/shot/domain/model.scala
- core/src/main/scala/com/karumi/shot/xml/ScreenshotsSuiteXmlParser.scala
- core/src/test/resources/screenshots-metadata/metadata.xml
- core/src/test/resources/screenshots-metadata/view-hierarchy.json
- core/src/test/scala/com/karumi/shot/domain/ConfigSpec.scala
- core/src/test/scala/com/karumi/shot/xml/ScreenshotsSuiteXmlParserSpec.scala
* **Issue:** Closes #82 
Update the Gradle plugin core components to be able to parse the new metadata format and the new files format used by recently published Facebook's library versions.
To implement this feature we've followed these steps:
* Change the configuration to use the latest release as the default dependency added when the plugin starts.
* Change how we parse the file xml metadata to match the new requirements.
* Update the coverage to use the new xml metadata.
* Change how we parse the view hierarchy json metadata.
* Update the coverage to use the new json metadata file.
* Change the code to unzip the pulled files from the device. We used a simple java library to do this.
* Update the project documentation reflecting the new change and also recommending a different snapshot …
> Update Facebook's lib support

- core/src/main/scala/com/karumi/shot/android/Adb.scala
* **Issue:** Closes #87 
Improve the log traces shown to the user when using adb.
We've configured a simple ``ProcessLogger``  instance when executing adb commands.
There is no need to add automated tests for these log traces.
> Add process logger to the usage of ADB

- shot-android/src/main/java/com/karumi/shot/ScreenshotTest.kt
* **Issue:** Fixes #114
Fix a crash found when ignoring webview activities.
We've moved the ignoredViews hide process to the target app main thread.
🤖
> Move hide ignored views to the target app thread

- core/src/main/scala/com/karumi/shot/Shot.scala
Add a message to the builds failing to show where they can find us in order to find some help with their app :smiley:
To implement this feature I've just changed the verification error message a little bit.
> Include help message

- shot-consumer-flavors/scripts/create_emulator.sh
- shot-consumer/scripts/create_emulator.sh
I mentioned this here: https://github.com/Karumi/Shot/issues/112#issuecomment-629179551
Allow running Shot sample scripts on MacOS Catalina. Running `$ANDROID_HOME/tools/mksdcard` fails with `bad CPU type in executable`.
By using the 64-bit mksdcard executable which is now part of the emulator tools package. The SDK Tools is compiled for 32-bit and - if I understand correctly - is no longer supported.
See: https://developer.android.com/studio/command-line#tools-emulator
By running one of `create_emulator.sh` scripts in Shot repo on MacOS Catalina.
Unfortunately I don't have a way to test this on Windows/Linux, so let's see if it passes on CI. :)
> Allow running emulator scripts on MacOS Catalina

- shot/src/main/scala/com/karumi/shot/ShotPlugin.scala
* **Issue:** Closes #128
* **Related pull-requests:** none
Reduce configuration time of every project that uses Shot. This is achieved by avoiding immediate task creation. 
Replace immediate task creation (`tasks.create`) with a lazy configuration (`tasks.register` + `taskProvider.configure`).
Implementation is based on Gradle recommendations for task avoidance: https://docs.gradle.org/current/userguide/task_configuration_avoidance.html
Execute `./gradlew help --scan` inside `shot-consumer` folder and check how many tasks are created by `Shot` plugin under "Performance" -> "Configuration" tab in the build scan report.
Before changes ([see build scan report](https://scans.gradle.com/s/flqilmsk3ouuy/performance/configuration?focused=20&openScriptsAndPlugins=WzFd)) 17 tasks are created …
> Create tasks lazily

- shot-android/build.gradle
- shot-android/src/main/java/com/karumi/shot/ScreenshotTest.kt
* **Issue:** Closes #131
Update Facebook library and disable the broken feature. More information can be found in the following links:
* https://github.com/facebook/screenshot-tests-for-android/issues/248
* https://github.com/facebook/screenshot-tests-for-android/pull/250
* https://github.com/facebook/screenshot-tests-for-android/pull/249
We've just changed the ``shot-android`` module to update the dependency and then we've updated ``ScreenshotTest`` interface to configure the screenshot builder with the ``setIncludeAccessibilityInfo`` param as ``false``.
This can not automatically be tested because it is a feature we've fixed in Facebook's library and adding a test to ensure the builder is properly configured is not worth it. The already implemented coverage will ensure the project is …
> Update Facebook library version to be able to disable accessibility features which are breaking the dialogs screenshots

- core/src/main/scala/com/karumi/shot/Shot.scala
- core/src/main/scala/com/karumi/shot/system/EnvVars.scala
- core/src/test/scala/com/karumi/shot/ShotSpec.scala
- shot/src/main/scala/com/karumi/shot/ShotPlugin.scala
- shot/src/main/scala/com/karumi/shot/tasks/Tasks.scala
* **Issue:** Closes #130
Update the plugin flow to review if the ``ANDROID_SERIAL`` env var is configured before interacting with the devices.
We've created a class to handle environment variables and also added some extra behavior to check how many devices are connected. Whenever the variable is present, we've altered the plugin flow to use only the specified device instead of all the available devices. Last but not least, I've added coverage to the feature in order to ensure everything is working as expected.
🤖
> Use ANDOROID_SERIAL env var when it is declared

- build.gradle
- shot-android/build.gradle
- shot-android/src/main/java/com/karumi/shot/ScreenshotTest.kt
- shot-android/src/main/java/com/karumi/shot/compose/ComposeScreenshot.kt
- shot-consumer-compose/app/build.gradle
- shot-consumer-compose/app/src/androidTest/java/com/karumi/shotconsumercompose/GreetingScreenshotTest.kt
- shot-consumer-compose/app/src/main/AndroidManifest.xml
- shot-consumer-compose/build.gradle
- shot-consumer-flavors/app/build.gradle
- shot-consumer-flavors/build.gradle
- shot-consumer/app/build.gradle
- shot-consumer/app2/build.gradle
- shot-consumer/build.gradle
- shot-consumer/samplelibrary/build.gradle
* **Issue:** #136
Define the public API we are going to provide to be able to take a screenshot of a Jetpack Compose component. This will be the API we will provide for the first version.
We've just added a new entry point in our ``ScreenshotTests`` interface accepting a ``SemanticsNodeInteraction`` which is the top type we will use in order to interact with Compose. To be able to do this we've updated the compose version up to alpha3 and also changed how ``disableFlakyComponentsAndWaitForIdle`` works to accept a nullable view. Once this was ready, we wrote some tests for the only component we have right now so you can see how the public API will be used.
Disclaimer: ``compareScreenshot`` behavior is not implemented for now. This will be part of my next PR.
🤖
> Jetpack Compose support public API

- release.gradle
* **Issue:** Fixes #139 
Ensure the sources jar distributed with shot-android contains shot-android's sources.
In release.gradle, replace "android.sourceSets.main.java.sourceFiles" with "android.sourceSets.main.java.srcDirs" as the property defining the location of the source files for Android modules.
Run `./gradlew androidSourcesJar`. Navigate to shot-android/build/lib and unzip the generated sources jar. Observe that it contains the module's source files, e.g. ScreenshotTest.kt.
> Correct Android source property in release.gradle

- README.md
- shot-android/src/main/java/com/karumi/shot/ScreenshotTest.kt
- shot-consumer-compose/app/src/androidTest/java/com/karumi/shotconsumercompose/GreetingScreenshotTest.kt
* **Issue:** #136 
Simplify the public API used to take a Jetpack Compose screenshot.
We've created a new entry point using a ``ComposeTestRule`` as a parameter instead of a ``SemanticNodeInteraction`` so we can easily take a screenshot. This new API works as a shortcut and simplifies a little bit our public API.
🤖
> Simplify Jetpack Compose public API

- README.md
- core/src/main/scala/com/karumi/shot/Shot.scala
- shot-android/src/main/java/com/karumi/shot/ScreenshotTest.kt
- shot-consumer-compose/app/src/androidTest/java/com/karumi/shotconsumercompose/GreetingScreenshotTest.kt
* **Issue:** #136 
Implement verification mode for Jetpack Compose.
To implement this feature we've updated the verification phase to use the code we already created in the previous PR. Once the screenshots are fetched and parsed, we only had to combine them with the regular Android screenshots in order to analyze the dependencies.
🤖  Now we have end to end tests ensuring everything is working like a charm.
> Verify mode for Jetpack Compose

- core/src/main/scala/com/karumi/shot/Files.scala
- core/src/main/scala/com/karumi/shot/android/Adb.scala
* **Issue:** #136 
Fix a bug found while using Shot in projects where there are only compose screenshot tests.
We've changed the way we pull the screenshots to show a warning if there is something wrong and also the code renaming the metadata files to be safer and do nothing if the source file does not exist.
🤖
> Improve error handling when there are only compose screenshots

- README.md
- shot-android/src/main/java/com/karumi/shot/ActivityScenarioUtils.kt
- shot-android/src/main/java/com/karumi/shot/ScreenshotTest.kt
- shot-consumer-flavors/app/build.gradle
- shot-consumer-flavors/app/src/androidTest/java/com/karumi/ui/view/AcceptanceTest.kt
* **Issue:** Closes #135 
Provide ``ActivityScenarioSupport``.
To implement this feature we've done our best...but the result is far from perfect 😢  The key to understanding this PR is to know the code extracting the class name and test name needs to be in the instrumentation thread. If we try to find the test name from the target app main thread the result will not be correct. So what did we do to solve this issue? We've created an extension method in ``ActivityScenario`` to be able to wait for the activity and return the instance to the instrumentation test thread. Just in case something changes the future we've also updated the code handling threads to ensure everything works as expected. Last but not least, we've changed one of the consumers to use ``ActivityScenario`` so we can use …
> Provide activity scenario support

- core/src/main/scala/com/karumi/shot/Shot.scala
- core/src/main/scala/com/karumi/shot/domain/model.scala
- core/src/main/scala/com/karumi/shot/screenshots/ScreenshotsComparator.scala
- shot-consumer-compose/app/build.gradle
- shot/src/main/scala/com/karumi/shot/ShotExtension.scala
Increase tolerance precision so we can configure tolerance values lower than 1 %
Just changing the extension type from ``Int`` to ``Double``.
🤖
> Increase tolerance precission

- shot-consumer-compose/app/build.gradle
- shot/src/main/scala/com/karumi/shot/ShotPlugin.scala
* **Issue:** Fixes #162 
Compose test application ID using variant API and not flavors' API
We've just changed the API we used to get the app id and the app suffix ID to use the expected ones. The one based on the variants is behaving properly on AGP >=4. I've added end-to-end tests to ensure everything is working as expected.
🤖
> Compose test application ID using variant API and not flavors' API

- README.md
- shot-android/src/androidTest/java/com/karumi/shot/compose/ScreenshotSaverTest.kt
- shot-android/src/main/java/com/karumi/shot/compose/ScreenshotSaver.kt
- shot-consumer-compose/app/src/androidTest/AndroidManifest.xml
* **Issue:** #120 
Due to the new storage system implemented on API 29 and higher, Shot is unable to write the screenshots on the SD. Shot can't be used at the moment with apps whose ``Target SDK is >= 30`` over ``devices with API >= 30``.
If one of those values (Target SDK or Device API) is <= 29,  Shot will work properly just adding the following parameter in the ``AndroidManifest.xml`` of the test app.
```
<application android:requestLegacyExternalStorage="true" />
```
A solution for Target SDK 30 and Device API 30 (an higher) execution is needed :S.
More information could be found in:
https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage
Just removed the harcoded limitation when Shot is working on Devices with API higher than 28.
Running screenshot tests …
> Shot Working on API 29+ in some cases

- shot-android/build.gradle
- shot-android/src/main/java/com/karumi/shot/ScreenshotTest.kt
- shot-consumer-compose/app/build.gradle
- shot-consumer-compose/app/src/main/java/com/karumi/shotconsumercompose/MainActivity.kt
- shot-consumer-compose/build.gradle
Updated compose version to lastest alpha. (alpha12), Also added a requires android O annotation to resolve a lint error following on from what had been done for another function
N/A
Ran all the units tests seemed fine although I did expect to have to update the kotlin version to 1.4.30 but seemed happy with the current version.
> Updated compose version to alpha12

- README.md
- core/src/main/scala/com/karumi/shot/Shot.scala
- shot/src/main/scala/com/karumi/shot/ShotPlugin.scala
- shot/src/main/scala/com/karumi/shot/tasks/Tasks.scala
* **Issue:** Fixes #199
Avoid a bug found after running a suite of tests two times where the first execution fails.
The ``Downloads`` folder is only configured to write content. We can't override it or rename it. If you think we can delete content, it's not your day. This was causing the second build after a failed execution to crash. This is the best fix I've found, cleaning the folder before and after running our tests.
There is no way I can write automated tests for this.
> Fix crash after build failure

- build.gradle
- core/src/main/scala/com/karumi/shot/Shot.scala
- core/src/main/scala/com/karumi/shot/android/Adb.scala
- core/src/main/scala/com/karumi/shot/base64/Base64Encoder.scala
- core/src/main/scala/com/karumi/shot/domain/model.scala
- core/src/main/scala/com/karumi/shot/json/ScreenshotsComposeSuiteJsonParser.scala
- core/src/main/scala/com/karumi/shot/reports/ConsoleReporter.scala
- core/src/main/scala/com/karumi/shot/reports/ExecutionReporter.scala
- core/src/main/scala/com/karumi/shot/screenshots/ScreenshotComposer.scala
- core/src/main/scala/com/karumi/shot/screenshots/ScreenshotsComparator.scala
- core/src/main/scala/com/karumi/shot/screenshots/ScreenshotsDiffGenerator.scala
- core/src/main/scala/com/karumi/shot/screenshots/ScreenshotsSaver.scala
- core/src/main/scala/com/karumi/shot/xml/ScreenshotsSuiteXmlParser.scala
- core/src/test/scala/com/karumi/shot/ShotSpec.scala
- core/src/test/scala/com/karumi/shot/domain/ConfigSpec.scala
- core/src/test/scala/com/karumi/shot/mothers/BuildTypeMother.scala
- core/src/test/scala/com/karumi/shot/xml/ScreenshotsSuiteXmlParserSpec.scala
- shot/src/main/scala/com/karumi/shot/ShotPlugin.scala
- shot/src/main/scala/com/karumi/shot/exceptions/ShotException.scala
- shot/src/main/scala/com/karumi/shot/tasks/Tasks.scala
* **Issue:** none
* **Related pull-requests:** #215
As requested in #215 I extracted `scalafmt` bump to a separate PR
I bumped scalafmt plugin to the most recent version and then executed `./gradlew scalafmtAll`. Bumping the dependency should reduce configuration time, as the new plugin doesn't download files from the internet at the configuraton time.
If it passes build and tests it should be fine I guess? No behavior changes are expected.
> Update scalafmt to 1.14.0

- shot/src/main/scala/com/karumi/shot/ShotPlugin.scala
Will allow overriding the configuration set in the gradle file with the commandline argument. 
e.g ./gradlew executeScreenshotTests -PrunInstrumentation=false
* **Issue:** Fixes #228 
Allow toggling the `runInstrumentation` property from the commandline
Check the gradle properties before defaulting to the usual config.
Can't see a way of writing any tests for this with the current test suite. Not very familiar with scala or with gradle plugins though so I'm happy to look at this again if I'm missing something.
> Support passing `runInstrumentation` flag as gradle argument

- core/build.gradle
- core/src/main/scala/com/karumi/shot/reports/ExecutionReporter.scala
- core/src/main/scala/com/karumi/shot/templates/RecordIndexTemplate.scala
- core/src/main/scala/com/karumi/shot/templates/VerificationIndexTemplate.scala
Fixes https://github.com/Karumi/Shot/issues/231
* **Issue:** #231
Fixes  gradle config cache issue caused by freemarker. 
Remove Freemarker and just use Scala String interpolation. 
Behavior should not change other than fixing the config cache warning when using this plugin.
> Remove freemarker.

- README.md
- core/src/main/scala/com/karumi/shot/Shot.scala
- core/src/main/scala/com/karumi/shot/domain/ShotFolder.scala
- core/src/main/scala/com/karumi/shot/domain/model.scala
- core/src/main/scala/com/karumi/shot/reports/ExecutionReporter.scala
- core/src/main/scala/com/karumi/shot/screenshots/ScreenshotsSaver.scala
- core/src/test/scala/com/karumi/shot/ProjectFolderMother.scala
- core/src/test/scala/com/karumi/shot/ShotSpec.scala
- core/src/test/scala/com/karumi/shot/domain/ConfigSpec.scala
- core/src/test/scala/com/karumi/shot/domain/ShotFolderSpec.scala
- core/src/test/scala/com/karumi/shot/mothers/BuildTypeMother.scala
- core/src/test/scala/com/karumi/shot/mothers/ProjectFolderMother.scala
- shot/src/main/scala/com/karumi/shot/ShotPlugin.scala
- shot/src/main/scala/com/karumi/shot/tasks/Tasks.scala
* **Issue:** https://github.com/pedrovgs/Shot/issues/86, https://github.com/pedrovgs/Shot/issues/258
This pull request aims to improve the directory management
`ShotFolder` class will be responsible of all directory structure. 
- Update `ShotExtension` to add `directoryPrefix` as an `Option`.   
And construct `ShotFolder` with this field when it's defined.
- Move hard coded file name & path from `Shot.scala` to `ShotFolder.scala`
> Directory suffix

- core/src/main/scala/com/karumi/shot/screenshots/ScreenshotsSaver.scala
* **Issue:** https://github.com/pedrovgs/Shot/issues/267
* **Related pull-request:** https://github.com/pedrovgs/Shot/pull/259/files#diff-453c09c8197e70a1c6195f40e55c1e4f8c1fd58f2eab38738a0abf0567059253L81
When we try to record compose screenshot. `ScreenshotsSaver#getScreenshotDimension` is not looking to the good path (see Related pull-request)
cf. Issue : If I clone the repo, delete the shot-consumer-compose/screenshots folder and run ./gradlew executeScreenshotTests -Precord on shot-consumer-compose
> Fix wrong path when getScreenshotDimension

- core/src/main/scala/com/karumi/shot/Shot.scala
- core/src/main/scala/com/karumi/shot/domain/ShotFolder.scala
- core/src/test/scala/com/karumi/shot/ShotSpec.scala
- core/src/test/scala/com/karumi/shot/domain/ShotFolderSpec.scala
- core/src/test/scala/com/karumi/shot/mothers/ProjectFolderMother.scala
- shot/src/main/scala/com/karumi/shot/tasks/Tasks.scala
* **Issue:** #244
Fixing error with existing files in pulled screenshot folder for regular and compose tests.
- Added removing `pulledScreenshotFolder` before downloading screenshots
- Removing both regular and compose `pulledScreenshotFolder`
- Added configuration of separation char in `ShotFolder` class
> [ISSUE-244] Fixed error with existing files in pulled screenshot folder

- core/src/main/scala/com/karumi/shot/Shot.scala
- core/src/main/scala/com/karumi/shot/json/ScreenshotsComposeSuiteJsonParser.scala
- core/src/test/resources/screenshots-metadata/compose-metadata.json
- core/src/test/resources/screenshots-metadata/empty-compose-screenshots-metadata.json
- core/src/test/scala/com/karumi/shot/json/ScreenshotsComposeSuiteJsonParserSpec.scala
* **Issue:** Closes #274
Processing of screenshot results on Compose fails because of the issue with Jackson being not able to create a reader to process JSON results. 
This is a workaround to parse those results without help of Jackson.
Instead of parsing the the `ComposeScreenshotSuite` with the help of Jackson, the manual parsing of AST implemented. This also aligns the parsing process with another implementation flow for legacy view system in `ScreenshotsSuiteJsonParser`, where the manual AST parsing happens.
I also did some refactoring to improve code structure in `ScreenshotsComposeSuiteJsonParser`.
> Fix Compose JSON parsing

- shot/src/main/scala/com/karumi/shot/ShotPlugin.scala
- shot/src/main/scala/com/karumi/shot/tasks/Tasks.scala
* **Issue:** Closes #263
Support Gradle configuration cache. 
* Avoid using project during task execution. Add extra parameters instead.
* Don't use BuildType as parameter. Use directly buildTypeName as parameter instead.
Ideally, I could enable configuration cache in `shot-consumer` project, but this requires to update AGP and Gradle. ~~Should I do the update? Do you prefer that I do it as current PR or as separate PR?~~ I see that there is a pending PR with an update. #288 
I don't know Scala. All changes were done just by following current code. Please keep that in mind during code review.
PS. BTW, having Kotlin as programming language would enable much more people to contribute.
> Support configuration cache

- core/src/main/scala/com/karumi/shot/Shot.scala
* **Issue:** Fixes #284
When running screenshot tests on multiple devices, we want all the screenshots for all devices and not only the latest.
Stop deleting the screenshot folder on each device, it is already deleted after the task is finished so it's not needed.
> [ISSUE-284] Don't override screenshots when running multiple devices

- README.md
- core/src/main/scala/com/karumi/shot/screenshots/ScreenshotsComparator.scala
* **Issue:** Fixes #282
Update our docs fixing an error in how tolerance values are configured and also replace ``>=`` comparison with ``>``. Thanks @adrinieto for reporting and the fix in your PR I'm applying here 😃 
Just docs updates and changing a small check.
🤖
> Update tolerance docs and fix bug in tolerance comparison

- core/src/main/scala/com/karumi/shot/reports/ExecutionReporter.scala
In the case of a screenshot test taking multiple screenshots per test it would be useful to have the name of the screenshot displayed in the test report. This PR adds this small change.
> Add screenshot name to test report

- core/src/main/scala/com/karumi/shot/Shot.scala
- core/src/main/scala/com/karumi/shot/android/Adb.scala
- core/src/test/scala/com/karumi/shot/ShotSpec.scala
- shot/src/main/scala/com/karumi/shot/ShotPlugin.scala
- shot/src/main/scala/com/karumi/shot/tasks/Tasks.scala
* **Issue:** https://github.com/pedrovgs/Shot/issues/263
* **Related pull-requests:**https://github.com/pedrovgs/Shot/pull/291
Ensure that configuration cache works after Gradle daemon is recreated.
* Avoid using global variable because Gradle has no idea about it and cannot recreate when configuration cache is reused. Use explicit task input instead.
* Annotate other task inputs.
* Convert internal "shot" property to function. It's used only once by each task anyway.
* `./gradlew debugExecuteScreenshotTests --configuration-cache`
* `./gradlew --stop`
* `./gradlew debugExecuteScreenshotTests --configuration-cache` - should display "Reusing configuration cache."
> Support configuration cache (second attempt)

- core/src/main/scala/com/karumi/shot/templates/VerificationIndexTemplate.scala
The emojis used in the verification template such as "❌" and "✅" are not rendered properly if the default charset of the OS is not UTF-8, ie a Windows machine may default to "Windows-1252" charset where the emojis aren't rendered. This is avoided by just specifying the charset in the meta tag in the HTML directly
> Ensure UTF-8 Charset for Verification HTML

- shot-android/src/main/java/com/karumi/shot/ScreenshotTest.kt
* **Issue:** https://github.com/pedrovgs/Shot/issues/253
To force failure when screenshot fails to record.
Added throw exception to ScreenshotTest
> Silent fail

- shot-android/src/main/java/com/karumi/shot/ScreenshotTest.kt
* **Issue:** https://github.com/pedrovgs/Shot/issues/264
To allow users to set max pixels when taking a screenshot. Currently, that is not allowed and screenshots will silently fail.
Added optional max size parameter to compareScreenshot
> added maxPixels to ScreenshotTest
